region            = "us-east4"
region_gke        = "us-central1"
google_project_id = "cbse-2024ii-438402"
registry_repo_id  = "docufam-reg"
isbn_db_pass      = "noteudc8362993"
network_id        = "docufam-net"
subnetwork_id     = "docufam-ms-subnet"
