version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: places_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: place-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
