version: '3.8'

services:

  dev_people_ms:
    build: .
    ports:
      - "5010:5010"
    depends_on:
      - mysql_db
    networks:
      - dev_people_net

  mysql_db:
    image: mysql:8.0
    container_name: people_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: people-db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - dev_people_net

networks:
  dev_people_net:
    driver: bridge
