@host = http://localhost:5030

### Get all cases
GET {{host}}/api/ComisaryCase
Accept: application/json

### Get a case by ID
GET {{host}}/api/ComisaryCase/3fa85f64-5717-4562-b3fc-2c963f66afa6
Accept: application/json

### Create a new case
POST {{host}}/api/ComisaryCase
Content-Type: application/json

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "title": "string",
  "patientId": "08dd01be-a178-49b9-8776-53835210ee01",
  "offenderId": "08dd01be-a178-49b9-8776-53835210ee01"
}
