name: Docker Image CD

on:
  push:
    branches: [ "main" ]

env:
  GCP_REGION: us-east4-docker.pkg.dev
  GCP_PROJECT_ID: cbse-2024ii-438402
  GCP_REPO_NAME: docufam-reg
  PLACE_MS_IMAGE_NAME: place-ms
  PEOPLE_MS_IMAGE_NAME: people-ms
  DOCS_MS_IMAGE_NAME: documents-ms
  API_GW_IMAGE_NAME: api-gw

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: Configure docker for GCP Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.GCP_REGION }}

    - name: Build and push Docker image PLACE-MS
      run: |
        cd ./place-ms
        docker build -t ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.PLACE_MS_IMAGE_NAME }}:latest .
        docker push ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.PLACE_MS_IMAGE_NAME }}:latest

    - name: Build and push Docker image PEOPLE-MS
      run: |
        cd ./people-ms
        docker build -t ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.PEOPLE_MS_IMAGE_NAME }}:latest .
        docker push ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.PEOPLE_MS_IMAGE_NAME }}:latest

    - name: Write Documents-ms Firestore Adm Secret to JSON file
      env:
        DOCS_FIRESTORE_ADMIN: ${{ secrets.DOCS_FIRESTORE_ADMIN }}
      run: |
        echo "${DOCS_FIRESTORE_ADMIN}" > ./documents-ms/Secrets/firestore-admin.json

    - name: Build and push Docker image DOCUMENTS-MS
      run: |
        cd ./documents-ms
        docker build -t ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.DOCS_MS_IMAGE_NAME }}:latest .
        docker push ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.DOCS_MS_IMAGE_NAME }}:latest

    - name: Build and push Docker image API GATEWAY
      run: |
        cd ./ApiGateway
        docker build -t ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.API_GW_IMAGE_NAME }}:latest .
        docker push ${{ env.GCP_REGION }}/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPO_NAME }}/${{ env.API_GW_IMAGE_NAME }}:latest
